#version: '3.8'

### SERVICES ###
services:
  nginx:
    image: nginx
    build: ./requirements/NGINX
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress_site_data:/var/www/wordpress:ro
      - ./requirements/NGINX/tools/default.conf:/etc/nginx/conf.d/default.conf
      - ./requirements/NGINX/tools/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/NGINX/tools/openssl.cnf:/openssl.cnf
    depends_on:
      - wordpress

  mariadb:
    image: mariadb
    build: ./requirements/MariaDB
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - wordpress_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    build: ./requirements/WordPress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    ports:
      - "9000:9000"
    volumes:
      - wordpress_site_data:/var/www/wordpress
    networks:
      - inception_net

### VOLUMES ###
networks:
  inception_net:
    driver: bridge

volumes:
  wordpress_db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/benpicar/data/wordpress_db
      o: bind

  wordpress_site_data:
    driver: local
    driver_opts:
      type: none
      device: /home/benpicar/data/wordpress_site
      o: bind
